apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-logger-space
  labels:
    app: json-logger-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-logger-space
  template:
    metadata:
      labels:
        app: json-logger-space
    spec:
      containers:
      - name: json-logger-space
        image: busybox
        command: ["/bin/sh"]
        args:
          - -c
          - |
            while true; do
              ts=$(date +"%Y-%m-%dT%H:%M:%SZ");
              rand=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1);
              echo "{ \"timestamp\" : \"$ts\", \"message\" : \"Dummy log data\", \"random\" : \"$rand\" }";
              sleep 5;
            done
